FROM mcr.microsoft.com/dotnet/core/sdk:3.1
COPY ./lib/armhf/* /usr/lib/
ADD ./bin/ /app/
ADD ./var/ /app/var/
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_URLS=http://*:80
CMD [ "dotnet", "maxbl4.RfidCheckpointService.dll" ]
